name: 🚀 Deploy to AlwaysData via FTP

on:
  push:
    branches:
      - main  # o la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 📤 Deploy to AlwaysData via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # sube todo el proyecto
          server-dir: ${{ secrets.FTP_PATH }}
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
